<?php

namespace AppBundle\Repository;

/**
 * citaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class citaRepository extends \Doctrine\ORM\EntityRepository
{
}
