<?php

namespace AppBundle\Repository;

/**
 * preferenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class preferenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
